/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nuhad' at '03/07/17 20:19' with Gradle 2.14.1
 *
 * @author nuhad, @date 03/07/17 20:19
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
